Test pipe (#27)
Co-authored-by: GitHub Action <action@github.com>

diff --git a/.github/workflows/build-feature.yml b/.github/workflows/build-feature.yml
--- a/.github/workflows/build-feature.yml
+++ b/.github/workflows/build-feature.yml
@@ -9,9 +9,7 @@ defaults:
   run:
     shell: bash
 
-permissions:
-  id-token: write   # This is required for requesting the JWT
-  contents: read    # This is required for actions/checkout
+permissions: write-all
 
 jobs:
   build:
@@ -47,6 +45,31 @@ jobs:
         run: |
           mvn package -Pnative -Dquarkus.application.name=atm-layer-model -Dquarkus.profile=prod 
 
+      - name: Create Status check based on postman results
+        id: process-postman
+        uses: im-open/process-postman-test-results@v2.1.5
+        with:
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          results-file: src/test/resources/integration-test/output/result.json
+          report-name: 'Postman ${{ github.run_number }}'
+          create-status-check: true
+          create-pr-comment: true
+          update-comment-if-one-exists: true
+          ignore-test-failures: true
+          timezone: 'europe/rome'
+
+      - name: Fail if there were errors in the postman tests
+        if: steps.process-postman.outputs.test-outcome == 'Failed'
+        run: |
+          echo "There were postman failures."
+          exit 1
+
+      - name: Upload result.html
+        uses: actions/upload-artifact@v3
+        with:
+          name: html-report
+          path: src/test/resources/integration-test/output/result.html
+
       - name: Build, tag, and push docker image to Amazon ECR
         env:
           REGISTRY: ${{ steps.login-ecr.outputs.registry }}
@@ -56,3 +79,4 @@ jobs:
           docker build -f src/main/java/it/gov/pagopa/atmlayer/service/model/docker/Dockerfile.native -t $REGISTRY/$REPOSITORY:$IMAGE_TAG . \
           --build-arg QUARKUS_PROFILE=prod \
           --build-arg APP_NAME=atm-layer-model
+ 
